import { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Legal Documents | Legal Search Hub",
  description:
    "Legal Disclaimer, Terms of Service, Privacy Policy, AI Usage Disclosure, and Acceptable Use Policy for Legal Search Hub.",
};

const LAST_UPDATED = "March 29, 2025";

const NAV = [
  { href: "#disclaimer", label: "Legal Disclaimer" },
  { href: "#terms", label: "Terms of Service" },
  { href: "#privacy", label: "Privacy Policy" },
  { href: "#ai-disclosure", label: "AI Usage Disclosure" },
  { href: "#acceptable-use", label: "Acceptable Use Policy" },
];

function SectionHeading({ id, number, title }: { id: string; number: string; title: string }) {
  return (
    <h2 id={id} className="text-2xl font-bold text-slate-900 mb-4 pt-2 flex items-center gap-3">
      <span className="text-sm font-bold text-blue-600 bg-blue-50 border border-blue-100 rounded-full px-3 py-1 shrink-0">
        {number}
      </span>
      {title}
    </h2>
  );
}

function BulletList({ items }: { items: string[] }) {
  return (
    <ul className="space-y-2 mb-6">
      {items.map((item, i) => (
        <li key={i} className="flex items-start gap-2.5 text-slate-600 text-sm leading-relaxed">
          <span className="w-1.5 h-1.5 rounded-full bg-blue-500 shrink-0 mt-2" />
          {item}
        </li>
      ))}
    </ul>
  );
}

export default function LegalPage() {
  return (
    <div className="min-h-screen bg-white">
      {/* Header */}
      <div className="bg-slate-900 py-14 px-4 text-center">
        <div className="max-w-3xl mx-auto">
          <Link href="/" className="inline-flex items-center gap-2 text-slate-400 hover:text-white text-sm mb-6 transition-colors">
            <span className="material-symbols-outlined text-base">arrow_back</span>
            Back to Legal Search Hub
          </Link>
          <div className="flex items-center justify-center gap-2 mb-4">
            <span className="material-symbols-outlined text-blue-400 text-2xl">gavel</span>
            <span className="font-bold text-white text-lg">Legal Search Hub</span>
          </div>
          <h1 className="text-3xl md:text-4xl font-bold text-white tracking-tight mb-3">
            Legal Documents
          </h1>
          <p className="text-slate-400 text-sm">Last Updated: {LAST_UPDATED}</p>
        </div>
      </div>

      <div className="max-w-3xl mx-auto px-4 py-12">
        {/* Table of contents */}
        <div className="bg-slate-50 border border-slate-200 rounded-2xl p-6 mb-12">
          <p className="text-xs font-bold uppercase tracking-widest text-slate-400 mb-4">
            Table of Contents
          </p>
          <ol className="space-y-2">
            {NAV.map((item, i) => (
              <li key={item.href}>
                <a
                  href={item.href}
                  className="flex items-center gap-3 text-sm text-blue-600 hover:text-blue-800 transition-colors"
                >
                  <span className="text-slate-400 font-mono text-xs w-5">{i + 1}.</span>
                  {item.label}
                </a>
              </li>
            ))}
          </ol>
        </div>

        {/* Divider */}
        <div className="border-t border-slate-100 mb-12" />

        {/* 1. Legal Disclaimer */}
        <section className="mb-14">
          <SectionHeading id="disclaimer" number="1" title="Legal Disclaimer" />
          <p className="text-slate-600 text-sm leading-relaxed mb-4">
            Legal Search Hub provides AI-generated legal information for general informational
            purposes only.
          </p>
          <BulletList items={[
            "Information is AI-driven and may be inaccurate, incomplete, or outdated.",
            "Legal Search Hub does not provide legal advice and does not create an attorney-client relationship.",
            "Accuracy is not guaranteed; jurisdictional limitations apply.",
            "Users assume all responsibility for decisions made using the app.",
            "Always consult a licensed attorney for advice specific to your situation.",
          ]} />
        </section>

        <div className="border-t border-slate-100 mb-12" />

        {/* 2. Terms of Service */}
        <section className="mb-14">
          <SectionHeading id="terms" number="2" title="Terms of Service" />
          <p className="text-slate-600 text-sm leading-relaxed mb-4">
            These Terms of Service govern your use of Legal Search Hub. By using the service,
            you agree to the following:
          </p>
          <BulletList items={[
            "Eligibility: Users must be 18 years of age or older, or of legal majority in their jurisdiction.",
            "AI content acknowledgment: You understand that answers are generated by AI and may not be accurate or current.",
            "No legal advice or representation: Nothing on this platform constitutes legal advice or creates an attorney-client relationship.",
            "Intellectual property: All content, branding, and technology on Legal Search Hub is the property of its owners. You may not reproduce or redistribute it without written permission.",
            "Account rules: You are responsible for maintaining the confidentiality of any account credentials and for all activity under your account.",
            "Limitation of liability: Legal Search Hub is not liable for any damages arising from your use of or reliance on the service.",
            "Indemnification: You agree to indemnify and hold Legal Search Hub harmless from any claims arising from your use of the service.",
            "Termination: Legal Search Hub reserves the right to suspend or terminate access for violations of these terms.",
            "Governing law: These terms are governed by the laws of the United States.",
            "Dispute resolution: Any disputes shall be resolved through binding arbitration in accordance with applicable law.",
          ]} />
        </section>

        <div className="border-t border-slate-100 mb-12" />

        {/* 3. Privacy Policy */}
        <section className="mb-14">
          <SectionHeading id="privacy" number="3" title="Privacy Policy" />
          <p className="text-slate-600 text-sm leading-relaxed mb-4">
            Legal Search Hub is committed to protecting your privacy. This policy describes
            how we collect, use, and protect your information.
          </p>
          <BulletList items={[
            "Data collection: We may collect your questions, jurisdiction selections, and usage data to operate and improve the service.",
            "AI processing: Queries submitted to the service may be processed by AI systems and stored to improve system performance.",
            "Cookies and tracking: We use cookies and analytics tools (including Google Analytics) to understand how users interact with the service.",
            "Third-party services: We use third-party providers including OpenAI, Vercel, Railway, and Google. Their privacy policies also apply.",
            "User rights: You have the right to access, correct, delete, or request portability of your personal data. Contact us at ask@legalsearchhub.com.",
            "Children: This service is not directed at children under 18. Parents may contact us to request removal of a minor's data.",
            "International transfers: Data may be transferred to and processed in countries outside your own.",
            "Changes: We may update this policy at any time. Continued use of the service constitutes acceptance of changes.",
          ]} />
        </section>

        <div className="border-t border-slate-100 mb-12" />

        {/* 4. AI Usage Disclosure */}
        <section className="mb-14">
          <SectionHeading id="ai-disclosure" number="4" title="AI Usage Disclosure" />
          <p className="text-slate-600 text-sm leading-relaxed mb-4">
            Legal Search Hub uses artificial intelligence to generate answers to legal questions.
            By using this service, you acknowledge the following:
          </p>
          <BulletList items={[
            "AI-generated content may be inaccurate, incomplete, or outdated. Laws change frequently and AI systems may not reflect the most current legal standards.",
            "This service is not a substitute for a licensed attorney. Nothing generated by this AI constitutes legal advice.",
            "No human review guarantee: Answers are generated automatically and are not reviewed by an attorney before being delivered.",
            "Jurisdictional variations apply: Laws differ significantly between states and countries. You are responsible for verifying that information applies to your jurisdiction.",
            "AI outputs may be used in anonymized, aggregated form to improve the service and train AI models.",
            "Citations provided link to official sources but the AI's interpretation of those sources may be incorrect. Always read the original source.",
          ]} />
        </section>

        <div className="border-t border-slate-100 mb-12" />

        {/* 5. Acceptable Use Policy */}
        <section className="mb-14">
          <SectionHeading id="acceptable-use" number="5" title="Acceptable Use Policy" />
          <p className="text-slate-600 text-sm leading-relaxed mb-4">
            Users of Legal Search Hub agree not to use the service in any of the following ways:
          </p>
          <BulletList items={[
            "Illegal activities: Using the service to plan, assist with, or carry out any unlawful act.",
            "Fraud or misrepresentation: Submitting false information or using the service to deceive others.",
            "Unauthorized practice of law: Using AI-generated answers to provide legal advice to third parties as if you were a licensed attorney.",
            "Abuse of legal systems: Using outputs to file frivolous claims, harass individuals, or abuse court processes.",
            "Malicious actions: Attempting to hack, disrupt, or interfere with the service or its underlying infrastructure.",
            "Data misuse: Scraping, harvesting, or redistributing data from the service without authorization.",
            "Enforcement: Legal Search Hub may monitor usage, suspend accounts, or terminate access for violations of this policy.",
            "Law enforcement cooperation: Legal Search Hub reserves the right to cooperate with law enforcement in connection with any investigation of unlawful activity.",
          ]} />
        </section>

        <div className="border-t border-slate-100 mb-12" />

        {/* Contact */}
        <div className="bg-blue-50 border border-blue-100 rounded-2xl p-6 text-center">
          <span className="material-symbols-outlined text-blue-500 text-2xl mb-2 block">mail</span>
          <p className="text-sm font-semibold text-slate-800 mb-1">Questions about these policies?</p>
          <a
            href="mailto:ask@legalsearchhub.com"
            className="text-blue-600 hover:text-blue-800 text-sm transition-colors"
          >
            ask@legalsearchhub.com
          </a>
        </div>

        {/* Back link */}
        <div className="text-center mt-10">
          <Link
            href="/"
            className="inline-flex items-center gap-2 text-slate-400 hover:text-blue-600 text-sm transition-colors"
          >
            <span className="material-symbols-outlined text-base">arrow_back</span>
            Back to Legal Search Hub
          </Link>
        </div>
      </div>
    </div>
  );
}
